[project]
name = "ampara-deep-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepagents==0.7.0",
    "langgraph>=1.0.0,<2.0",
    "langchain>=1.0.0,<2.0",
    "langchain-core>=1.3.3,<2.0",
    "langchain-openai",
    "langchain-community>=0.4.2",
    "langchain-quickjs",
    "langchain-mcp-adapters",
    "langchain-postgres",
    "psycopg[binary]",
    "python-dotenv"
]
